services:
  storage:
    image: redis

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwerty

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://root:qwerty@mongo:27017/

  counter:
    build: ./counter
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    ports:
      - 3001:3001
    depends_on:
      - storage

  api:
    build: ./api
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter:3001
      - URL_MONGO=mongodb://root:qwerty@mongo:27017/
    ports:
      - 80:3000
    depends_on:
      - mongo
